FROM gradle:7.5.1-jdk17-alpine AS build

COPY --chown=gradle:gradle ../backend /home/gradle/src

WORKDIR /home/gradle/src

RUN gradle bootJar --no-daemon

FROM alpine:latest

# Install OpenJDK and Graphviz for graph generation
RUN apk add openjdk17 && apk add graphviz
# Install fonts as Graphviz has libraries which use system installed fonts
RUN apk add terminus-font ttf-inconsolata ttf-dejavu font-noto font-noto-cjk ttf-font-awesome font-noto-extra

# Copy JAR to container
ARG JAR_FILE=web-0.0.1-SNAPSHOT.jar
COPY --from=build /home/gradle/src/build/*.jar app.jar

# Make directories used by the generators
# src-gen is the standard directory
RUN mkdir src-gen
RUN mkdir ./tmp/GraphvizJava

ENTRYPOINT ["java", "-jar", "/app.jar"]